spring:
  application:
    name: limitedgoods

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/limitedgoods}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:fbwls9663}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      timeout: 6000ms

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      properties:
        spring:
          json:
            trusted:
              packages: com.limitedgoods.limitedgoods.*

server:
  tomcat:
    threads:
      max: 200

jwt:
  secret: limitedgoods-secret-key-must-be-at-least-256-bits-long
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      show-details: always

  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: INFO

    com.limitedgoods: DEBUG

    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

    org.springframework.security: WARN