spring.application.name=limitedgoods
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/limitedgoods}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:fbwls9663}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

jwt.secret=limitedgoods-secret-key-must-be-at-least-256-bits-long
jwt.expiration=86400000

spring.datasource.hikari.maximum-pool-size=10
server.tomcat.threads.max=200

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.timeout=6000ms

# Prometheus 엔드포인트 노출
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true

#logging.pattern.console=%d{HH:mm:ss} [%-5level] [%thread] %logger{36} - %msg%n

# 기본 레벨 - INFO 이상만 출력 (DEBUG 숨김)
logging.level.root=INFO

# 내 코드만 DEBUG까지 출력
logging.level.com.limitedgoods=DEBUG

# Hibernate SQL 쿼리 보고 싶으면
logging.level.org.hibernate.SQL=DEBUG

# Hibernate 파라미터 값까지 보고 싶으면
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Spring Security 로그 숨기기
logging.level.org.springframework.security=WARN