apiVersion: 1

datasources:
  - name: Prometheus
    uid: limitedgoods-prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s